name: Test Time Tracking Backend

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install the dependencies
        run: npm install

      - name: Unit Test
        run: npm run test:cov

  e2e-test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: mysql://root:password@localhost:3306/timetracking-e2e
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_ROOT_HOST: '%'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install the dependencies
        run: npm install

      - name: Migrate database
        run: npx prisma migrate deploy

      - name: E2E Test
        run: npm run test:e2e
